Persky Idan 215548512 , Golan Amir 216264333

# Lab 02 – NumPy & Pandas: Working with Real Data
**Data Science Lab 83-554 · Bar-Ilan University · Dr. Alexandra Litinsky Simanovsky**

You already know NumPy and Pandas. Today you will use them the way a data scientist does: on real, imperfect data, where the hard part is not the syntax but deciding what to do.

| Block | Topic | Time |
|---|---|---|
| 0 | Warm-up (25 quick exercises) | ~25 min |
| 1 | NumPy on real clinical data (METABRIC breast-cancer cohort) | ~55 min |
| 2 | Pandas on real academic data (student enrollment & dropout) | ~95 min |
| 3 | Find the bug | ~25 min |
| 4 | Integrated challenge | ~35 min |
| 5 | Working with an LLM – critically | ~15 min |

**How to work**
- Each exercise shows the **expected output** under an empty cell. Write code that produces it, then run the cell – your output replaces the expected one.
- Hints are collapsed under each exercise. Try first, open them only if you are stuck.
- Where an exercise says *explain*, write your answer in a short comment or a Markdown cell.
- Warm-up exercises are adapted from the 100-exercise notebook prepared by the course teaching assistants.
- Expected outputs were produced with NumPy 2 / pandas 2.2. On NumPy 1.x a scalar prints as `3` instead of `np.int64(3)` – that is fine.
- Several questions ask you to *discover* a fact in the data before deciding what to do. State your decision in a comment; it is part of the answer.

**Data** (folder `data/`)
- `metabric_clinical.csv` – 1,900 breast-cancer patients from the METABRIC cohort (cBioPortal), clinical attributes.
- `students_enrollment.csv` – 3,358 university enrollments with first-year results and final outcome (adapted from UCI ML Repository #697; the course staff added `enrollment_date` and a few realistic data problems).
- `course_codes_v2.csv` – an 'updated' lookup a colleague sent (used in Block 3).
- `course_codes.csv` – lookup table: course code → course name and department.

## Block 0 – Warm-up (~25 min)
Quick exercises on small in-memory data, adapted from the TA notebook. Aim for one line each.

**Optional in class.** If these feel easy, do the first five, skip to Block 1, and finish the rest at home before the next lab. The real work starts in Block 1.

In [1]:
import numpy as np
import pandas as pd
temperatures_w1 = np.array([22.5, 25.3, 20.8, 23.4, 26.1, 24.8, 21.9])
temperatures_w2 = np.array([19.2, 22.5, 21.3, 24.0, 23.5, 22.8, 20.1])
temperatures_w1, temperatures_w2

(array([22.5, 25.3, 20.8, 23.4, 26.1, 24.8, 21.9]),
 array([19.2, 22.5, 21.3, 24. , 23.5, 22.8, 20.1]))

### Exercise 1

Convert the Week 1 temperatures from Celsius to Fahrenheit.

In [2]:
# Write your code here
temperatures_w1_F = temperatures_w1 *(9/5)+32
temperatures_w1_F

array([72.5 , 77.54, 69.44, 74.12, 78.98, 76.64, 71.42])

### Exercise 2

Find the standard deviation of the Week 1 temperatures.

In [3]:
# Write your code here
std = np.std(temperatures_w1)
std

np.float64(1.7943221106408669)

### Exercise 3

Find all Week 1 temperatures between 22°C and 25°C inclusive.

In [4]:
# Write your code here
temperatures_w1_conditions = temperatures_w1[(temperatures_w1 > 22) & (temperatures_w1 < 25)]
temperatures_w1_conditions

array([22.5, 23.4, 24.8])

### Exercise 4

Count how many Week 1 temperatures are above the weekly mean.

In [5]:
# Write your code here
temperatures_w1_above_mean = temperatures_w1[temperatures_w1 > temperatures_w1.mean()]
print(temperatures_w1.mean())
temperatures_w1_above_mean

23.542857142857144

array([25.3, 26.1, 24.8])

### Exercise 5

Round all Week 1 temperatures to the nearest whole number. One value will surprise you – explain it in a comment.

In [6]:
# Write your code here
round_temp = temperatures_w1.round()
print(temperatures_w1)
round_temp

[22.5 25.3 20.8 23.4 26.1 24.8 21.9]

array([22., 25., 21., 23., 26., 25., 22.])

<details><summary><b>Hint 1</b></summary>

Look at the first value: 22.5 became 22, not 23. Search: 'round half to even'.

</details>

### Exercise 6

Create a 2D array `temperatures` with Week 1 as the first row and Week 2 as the second. Show its shape.

In [7]:
# Write your code here
twoD_temp = np.array([(temperatures_w1),(temperatures_w2)])
twoD_temp

array([[22.5, 25.3, 20.8, 23.4, 26.1, 24.8, 21.9],
       [19.2, 22.5, 21.3, 24. , 23.5, 22.8, 20.1]])

### Exercise 7

Extract the weekend temperatures (last two days) for both weeks.

In [8]:
# Write your code here
twoD_temp[:,-2:]

array([[24.8, 21.9],
       [22.8, 20.1]])

### Exercise 8

Find the mean temperature of each week.

In [9]:
# Write your code here
mean_arr = np.array([(twoD_temp[0].mean()),(twoD_temp[1].mean())])
mean_arr

array([23.54285714, 21.91428571])

### Exercise 9

Find the mean temperature for each day across the two weeks.

In [10]:
# Write your code here
mean_arr = np.mean(twoD_temp,axis=0)
mean_arr

array([20.85, 23.9 , 21.05, 23.7 , 24.8 , 23.8 , 21.  ])

### Exercise 10

Find the (row, column) position of the overall maximum using `argmax` and `unravel_index`.

In [11]:
# Write your code here
maxval_loc = np.argmax(twoD_temp)
row, col = np.unravel_index(maxval_loc,twoD_temp.shape)
row, col

(np.int64(0), np.int64(4))

### Exercise 11

On which days was Week 1 warmer than Week 2? Return a boolean array.

In [12]:
# Write your code here
one_warmer_two = [temperatures_w1>temperatures_w2]
one_warmer_two

[array([ True,  True, False, False,  True,  True,  True])]

### Exercise 12

Find all values in the 2D array that are above the overall mean.

In [13]:
# Write your code here
twoD_mean = np.mean(twoD_temp)
twoD_temp[twoD_temp>twoD_mean]

array([25.3, 23.4, 26.1, 24.8, 24. , 23.5, 22.8])

In [14]:
marks = pd.Series([95, 92, 89, 85, 80], index=['Rank1', 'Rank2', 'Rank3', 'Rank4', 'Rank5'])
marks

Rank1    95
Rank2    92
Rank3    89
Rank4    85
Rank5    80
dtype: int64

### Exercise 13

Retrieve the top three ranks using `.loc` with a label slice.

In [15]:
# Write your code here
marks.loc['Rank1':'Rank3']

Rank1    95
Rank2    92
Rank3    89
dtype: int64

### Exercise 14

Find the index label of the highest mark.

In [16]:
# Write your code here
marks.argmax()

np.int64(0)

### Exercise 15

Count how many students scored at least 90.

In [17]:
# Write your code here
len(marks[marks>90])

2

### Exercise 16

In a **copy** of the Series, change `Rank1` to 100. Show the copy and prove the original is unchanged.

In [18]:
# Write your code here
marks_copy = marks.copy()
marks_copy['Rank1']=100
marks_copy

Rank1    100
Rank2     92
Rank3     89
Rank4     85
Rank5     80
dtype: int64

### Exercise 17

Sort the Series by its index labels in descending order.

In [19]:
# Write your code here
marks_copy.sort_values(ascending=False)

Rank1    100
Rank2     92
Rank3     89
Rank4     85
Rank5     80
dtype: int64

### Exercise 18

Subtract the mean mark from every student's mark.

In [20]:
# Write your code here
mean_marks = marks_copy.mean()
print(mean_marks)
marks_copy_mean_subtracted = marks_copy - mean_marks
marks_copy_mean_subtracted

89.2

Rank1    10.8
Rank2     2.8
Rank3    -0.2
Rank4    -4.2
Rank5    -9.2
dtype: float64

In [21]:
transactions = pd.DataFrame({
    'TransactionID': [101,102,103,104,105,106,107,108,109,110],
    'ProductCategory': ['Electronics','Clothing','Electronics','Furniture','Clothing',
                        'Electronics','Furniture','Clothing','Furniture','Electronics'],
    'Region': ['North','South','North','East','West','North','East','West','South','North'],
    'Amount': [200,150,300,450,200,250,300,180,350,400]
})
transactions

   TransactionID ProductCategory Region  Amount
0            101     Electronics  North     200
1            102        Clothing  South     150
2            103     Electronics  North     300
3            104       Furniture   East     450
4            105        Clothing   West     200
5            106     Electronics  North     250
6            107       Furniture   East     300
7            108        Clothing   West     180
8            109       Furniture  South     350
9            110     Electronics  North     400

### Exercise 19

Retrieve the last 3 columns using `.iloc`.

In [22]:
# Write your code here
transactions.iloc[:,-3:]

  ProductCategory Region  Amount
0     Electronics  North     200
1        Clothing  South     150
2     Electronics  North     300
3       Furniture   East     450
4        Clothing   West     200
5     Electronics  North     250
6       Furniture   East     300
7        Clothing   West     180
8       Furniture  South     350
9     Electronics  North     400

### Exercise 20

Filter rows where Region is `North` **and** Amount is greater than 200.

In [23]:
# Write your code here
conditions = transactions.query('Region=="North" and Amount>200' )
conditions

   TransactionID ProductCategory Region  Amount
2            103     Electronics  North     300
5            106     Electronics  North     250
9            110     Electronics  North     400

### Exercise 21

Filter rows where Region is `East` or `West` – without using `|`.

In [24]:
# Write your code here
conditions = transactions.query('Region in ["West","East"]')
conditions

   TransactionID ProductCategory Region  Amount
3            104       Furniture   East     450
4            105        Clothing   West     200
6            107       Furniture   East     300
7            108        Clothing   West     180

### Exercise 22

Return the full row of the transaction with the highest Amount.

In [25]:
# Write your code here
transactions.loc[transactions['Amount'].idxmax()]

TransactionID            104
ProductCategory    Furniture
Region                  East
Amount                   450
Name: 3, dtype: object

### Exercise 23

Sort first by Region (ascending) and then by Amount (descending).

In [26]:
# Write your code here
transactions.sort_values('Region',ascending=True)
transactions.sort_values('Amount',ascending=False)

   TransactionID ProductCategory Region  Amount
3            104       Furniture   East     450
9            110     Electronics  North     400
8            109       Furniture  South     350
2            103     Electronics  North     300
6            107       Furniture   East     300
5            106     Electronics  North     250
4            105        Clothing   West     200
0            101     Electronics  North     200
7            108        Clothing   West     180
1            102        Clothing  South     150

### Exercise 24

Find both the mean and the maximum Amount for each ProductCategory, in one table.

In [27]:
# Write your code here
maxval = transactions.groupby('ProductCategory').max().reset_index()
meanval = transactions.groupby('ProductCategory')['Amount'].mean()
print(meanval)
print(maxval)

ProductCategory
Clothing       176.666667
Electronics    287.500000
Furniture      366.666667
Name: Amount, dtype: float64
  ProductCategory  TransactionID Region  Amount
0        Clothing            108   West     200
1     Electronics            110  North     400
2       Furniture            109  South     450

### Exercise 25

Find the Region with the highest total Amount, and the total itself.

In [28]:
# Write your code here
transactions.loc[transactions['Amount'].idxmax()]['Region']

'East'

## Block 1 – NumPy on real clinical data (~55 min)
**METABRIC** is a cohort of breast-cancer patients with clinical follow-up. We will work on five numeric measurements as a plain NumPy matrix:
`age_at_diagnosis`, `tumor_size_mm`, `lymph_nodes_positive`, `npi` (Nottingham Prognostic Index), `survival_months`.

The habits this block trains: check for missing values before computing anything, ask what a missing value *means* before filling it, use broadcasting instead of loops, and know when you are looking at a copy and when at a view. Some questions ask for a number that only this file can give you – that is on purpose.

In [29]:
clinical = pd.read_csv('Data/metabric_clinical.csv')
features = ['age_at_diagnosis', 'tumor_size_mm', 'lymph_nodes_positive', 'npi', 'survival_months']
X = clinical[features].to_numpy(dtype=float)
print(X.shape, X.dtype)
X[:3]

(1900, 5) float64

array([[ 50.08      ,  20.        ,   0.        ,   4.04      ,
        267.26666667],
       [ 56.85      ,   9.        ,   1.        ,   4.018     ,
        153.83333333],
       [ 28.37      ,  20.5       ,   3.        ,   5.041     ,
        195.36666667]])

### Exercise 26 – Missing values per column

How many missing values (`NaN`) does each of the five columns have? Return one array of 5 counts.

In [30]:
# Write your code here
clinical[features]
sum(np.isnan(X))

array([  9, 109, 188, 163, 391])

<details><summary><b>Hint 1</b></summary>

`np.isnan` returns a boolean array of the same shape.

</details>
<details><summary><b>Hint 2</b></summary>

Sum booleans along `axis=0` to count per column.

</details>

### Exercise 27 – NaN-aware statistics

Compute the mean of each column twice: once with `X.mean(axis=0)` and once with `np.nanmean`. Explain in a comment why the two results differ and which one is correct here.

In [31]:
# Write your code here
features = ['age_at_diagnosis', 'tumor_size_mm', 'lymph_nodes_positive', 'npi', 'survival_months']
print(clinical[features].mean(axis=0),"\n")
np.nanmean(clinical[features], axis=0)

age_at_diagnosis         60.824627
tumor_size_mm            26.414629
lymph_nodes_positive      1.986565
npi                       4.030349
survival_months         125.049812
dtype: float64

array([ 60.82462718,  26.4146287 ,   1.98656542,   4.03034907,
       125.04981224])

<details><summary><b>Hint 1</b></summary>

NaN 'infects' every arithmetic operation.

</details>
<details><summary><b>Hint 2</b></summary>

`np.nanmean`, `np.nanmedian`, `np.nanstd` ignore NaN.

</details>

### Exercise 28 – What does a missing value mean?

**Before you fill anything, find out what the missing values mean.** Use the `clinical` DataFrame for this one:
(a) Show that `survival_months` is missing for **exactly** the patients whose `survival_status` is missing (print both counts and the count of rows where both are missing).
(b) Print the mean `survival_months` for `LIVING` and for `DECEASED` patients.
(c) In two comment lines: what does `survival_months` measure for a *living* patient, and why would filling its missing values with the column median be wrong?

In [32]:
# A: The missing values mean: survival months: The amount of time the patiant survived cancer.
# Survival status: whether the patiant is alive or deceased. 
both_missing = len(clinical[clinical["survival_months"].isna() & clinical["survival_status"].isna()])
print(f"features where both have missing values{both_missing}")
missing_months = len(clinical[clinical["survival_months"].isna()])
print(f"values where only survival months are missing {missing_months}")

# B:
mean_living = clinical[clinical['survival_status'] == 'LIVING']['survival_months'].mean()
print(f"The current mean for living patients is {mean_living} months")
mean_dead = clinical[clinical['survival_status'] == 'DECEASED']['survival_months'].mean()
print(f"The current mean for living patients is {mean_dead} months")

# C: We can see the severity of the stage of the patient and filling it's missing values can mislead us.

features where both have missing values391
values where only survival months are missing 391
The current mean for living patients is 159.25636645962734 months
The current mean for living patients is 99.58273603082851 months

<details><summary><b>Hint 1</b></summary>

`.isna()` on both columns, then `&` to combine.

</details>
<details><summary><b>Hint 2</b></summary>

`groupby('survival_status')['survival_months'].mean()`.

</details>
<details><summary><b>Hint 3</b></summary>

Think about what the number means for someone who is still alive.

</details>

### Exercise 29 – Median imputation, where it is justified

Now impute **only the first four columns** (age, tumor size, lymph nodes, NPI) with the **median of their own column**, without a loop, into a copy `X_filled`. Leave `survival_months` as it is. Verify: how many NaN remain in `X_filled`, and in which column? `X` itself must be unchanged.

In [33]:
# Write your code here
four_columns = ['age_at_diagnosis', 'tumor_size_mm', 'lymph_nodes_positive', 'npi']
X_filled = clinical.copy()
medians = np.nanmedian(X_filled[four_columns], axis=0)
nan_mask = np.isnan(X_filled[four_columns])
X_filled = np.where(nan_mask,medians,X_filled[four_columns])
sum(np.isnan(X_filled))

array([0, 0, 0, 0])

<details><summary><b>Hint 1</b></summary>

`np.nanmedian(X, axis=0)` gives one median per column (shape `(5,)`).

</details>
<details><summary><b>Hint 2</b></summary>

`np.where(condition, value_if_true, value_if_false)` – a `(4,)` vector broadcasts against a `(1900, 4)` block.

</details>
<details><summary><b>Hint 3</b></summary>

Slice the first four columns on both sides of the assignment.

</details>

### Exercise 30 – Z-scores by broadcasting

Standardize the **first four columns** of `X_filled` to z-scores (`(x - mean) / std` per column) **in a single expression** with no loop. Store the result in `Z` (shape `(1900, 4)`). Verify: column means ≈ 0 and column standard deviations ≈ 1. Write the shapes of the two operands in a comment.

In [34]:
# Write your code here
Z=(X_filled[:,0:4] - np.mean(X_filled[:,0:4]))/np.std(X_filled[:,0:4])
print(f"The mean is: {Z.mean()}")
print(f"The Deviation is: {Z.std()}")
Z.shape

The mean is: -1.7950553324465689e-16
The Deviation is: 1.0

(1900, 4)

<details><summary><b>Hint 1</b></summary>

`X4.mean(axis=0)` has shape `(4,)`. Subtracting it from a `(1900, 4)` matrix works by broadcasting.

</details>
<details><summary><b>Hint 2</b></summary>

Broadcasting aligns trailing dimensions: `(1900, 4)` and `(4,)` match on the last axis.

</details>

### Exercise 31 – Copy vs view

**Copy or view?** The cell below is intentionally wrong. Run it and look at `X_filled[:3, 0]` afterwards. Explain in a comment what happened. Then fix it so that `ages_capped` holds the ages capped at 70 **without** changing `X_filled` (restore `X_filled` from `X` first). *The expected output below is from the corrected version.*

In [35]:
# This code runs without an error but gives a wrong result. Find the bug, explain it.
# ages = X_filled[:, 0] We will change this to a copy! 
ages = X_filled[:,0].copy()
min = np.minimum(ages, 70, out=ages)
print(min)
# And we will run exercise 29 again to fix X_filled:
four_columns = ['age_at_diagnosis', 'tumor_size_mm', 'lymph_nodes_positive', 'npi']
X_filled = clinical.copy()
medians = np.nanmedian(X_filled[four_columns], axis=0)
nan_mask = np.isnan(X_filled[four_columns])
X_filled = np.where(nan_mask,medians,X_filled[four_columns])

[50.08 56.85 28.37 ... 56.93 62.91 54.96]

<details><summary><b>Hint 1</b></summary>

Basic slicing (`X[:, 0]`, `X[2:5]`) returns a **view**: same memory, different window.

</details>
<details><summary><b>Hint 2</b></summary>

`.copy()` gives independent memory. Fancy/boolean indexing (`X[[0, 2]]`, `X[X > 0]`) also returns copies.

</details>

### Exercise 32 – Boolean masks

Using boolean masks on `X_filled`: how many patients were diagnosed **under 40** with a tumor **larger than 30 mm**? What percentage of the cohort is that? Print both (1 decimal for the percentage).

In [36]:
# Write your code here
# The answer is count 24 and percent 1.3%
count=0
condition_mask = (X_filled[:, 0] < 40) & (X_filled[:, 1] > 30)
count = np.count_nonzero(condition_mask)
print(f"The amount of patients that are under 40 with tumor size of 30+ are: {count}")
print(f"That yeilds {((count/len(X_filled))*100):.2f}% of all patients")

The amount of patients that are under 40 with tumor size of 30+ are: 24
That yeilds 1.26% of all patients

<details><summary><b>Hint 1</b></summary>

Combine conditions with `&`, each in parentheses.

</details>
<details><summary><b>Hint 2</b></summary>

The mean of a boolean array is the fraction of `True`.

</details>

### Exercise 33 – argsort and ties

Find the 10 patients with the **highest NPI** (column index 3) using `argsort`, and return their **ages sorted from oldest to youngest** (1 decimal). Several patients share the same NPI – why does asking for the ages *sorted* make the expected output unambiguous? Answer in a comment.

In [37]:

top_10_indices = np.argsort(X_filled[:, 3])[-10:]
top_10_ages = np.round(X_filled[top_10_indices, 0], 1)
result_ages = np.sort(top_10_ages)[::-1]
print(result_ages)

# Answer: Because multiple patients can have identical NPI values, the sorting can choose unabiguously the patients
# This means the subset of 10 patients (and their order) can change. 
# When we sort it by age it could be more unique.

[79.9 78.9 66.8 65.  56.8 56.2 50.  46.5 41.5 32.9]

<details><summary><b>Hint 1</b></summary>

`np.argsort` returns the indices that would sort the array, ascending.

</details>
<details><summary><b>Hint 2</b></summary>

Reverse with `[::-1]`, take the first 10, then use the indices on another column.

</details>
<details><summary><b>Hint 3</b></summary>

Ties: `np.argsort(-x)` and `np.argsort(x)[::-1]` can pick different rows among equal values. Sorting the final ages makes the answer order-independent.

</details>

### Exercise 34 – Vectorized categorization

Create an array `age_group` of strings with the labels `'<50'`, `'50-70'` (50 to 70 **inclusive**), `'>70'` according to each patient's age. Count how many patients are in each group with `np.unique(..., return_counts=True)`.

In [38]:
# Write your code here
ages = X_filled[:, 0]

conditions = [ages < 50, (ages >= 50) & (ages <= 70), ages > 70]
choices = ['<50', '50-70', '>70']
age_group = np.select(conditions, choices, default='Unknown')

print(np.unique(age_group, return_counts=True))

(array(['50-70', '<50', '>70'], dtype='<U7'), array([985, 422, 493]))

<details><summary><b>Hint 1</b></summary>

`np.select([cond1, cond2], [label1, label2], default=label3)` – conditions are checked in order; `default` must be a string too, or NumPy raises a dtype error.

</details>
<details><summary><b>Hint 2</b></summary>

Or nest two `np.where` calls.

</details>

### Exercise 35 – All-pairs distances: broadcasting vs the Gram trick

**All-pairs distances, the engineering way.**
(a) Using the first 300 rows of `Z`, compute the pairwise Euclidean distance matrix `D300` of shape `(300, 300)` **without a loop**, via 3-D broadcasting `(300,1,4) - (1,300,4)`.
(b) *Before running anything*, compute by hand (in a comment) how many **MB** the intermediate `(1900, 1900, 4)` float64 array would take if you did the same for all patients.
(c) Compute the full `(1900, 1900)` matrix `D` **without the 3-D intermediate**, using the identity ‖a−b‖² = ‖a‖² + ‖b‖² − 2·a·b (one matrix product). Clip tiny negatives to 0 before the square root.
(d) Check with `np.allclose(..., atol=1e-6)` that `D[:300, :300]` equals `D300` (why is a tolerance needed on the diagonal?), and print the index of the patient most similar to patient 0 (excluding patient 0).

In [39]:
# Write your code here
# (a) Pairwise Euclidean distance for the first 300 rows using 3-D broadcasting
Z300 = Z[:300]
# Broadcasting shape: (300, 1, n_features) - (1, 300, n_features) -> (300, 300, n_features)
diff = Z300[:, np.newaxis, :] - Z300[np.newaxis, :, :]
D300 = np.sqrt(np.sum(diff**2, axis=-1))

# (b) Intermediate memory calculation:
# 1900 * 1900 * 4 elements * 8 bytes (float64) = 115,520,000 bytes which is 115.52 MB

# (c) Using the identidy we will calculate the matrix D
Z_sq = np.sum(Z**2, axis=1, keepdims=True)
D_sq = Z_sq + Z_sq.T - 2 * np.dot(Z, Z.T)
D = np.sqrt(np.clip(D_sq, 0, None)) # Clip limits the tiny negatives to 0 as requested

# (d) Check with np.allclose and find the most similar patient to patient 0 (excluding patient 0)
# (d) Checking with np.allclose that D[:300,:300] is equal to D300
is_close = np.allclose(D[:300, :300], D300, atol=1e-6)

# Why tolerance is needed on the diagonal: 
# Floating-point arithmetic inaccuracies can result in tiny negative values 
# (for example -1e-15) on the self-distance diagonal when evaluating a^2 + a^2 - 2a^2, 
# which need to be clipped or handled with a tolerance.

# Find the most similar patient to patient 0 (excluding patient 0 itself)
D_copy = D[0].copy()
D_copy[0] = np.inf  # Ignore distance to self
nearest_patient = np.argmin(D_copy)
nearest_distance = D_copy[nearest_patient]

print(f"allclose: {is_close} | D shape: {D.shape} | nearest to patient 0: {nearest_patient} | distance: {nearest_distance:.3f}")

allclose: True | D shape: (1900, 1900) | nearest to patient 0: 1091 | distance: 0.022

<details><summary><b>Hint 1</b></summary>

`A[:, np.newaxis, :]` has shape `(300, 1, 4)`; `A[np.newaxis, :, :]` has shape `(1, 300, 4)`. Subtracting them broadcasts to `(300, 300, 4)`.

</details>
<details><summary><b>Hint 2</b></summary>

Memory: number of elements × 8 bytes (float64).

</details>
<details><summary><b>Hint 3</b></summary>

Row norms squared: `(Z**2).sum(axis=1)`; the cross term is `Z @ Z.T`. Shapes `(1900,1)` + `(1,1900)` − `(1900,1900)`.

</details>
<details><summary><b>Hint 4</b></summary>

Floating-point error can give −1e-15 on the diagonal; `np.clip(D2, 0, None)` before `sqrt`. After the sqrt that error becomes ~1e-7, larger than `allclose`'s default `atol=1e-8` – hence the tolerance.

</details>

### Exercise 36 – Bootstrap confidence interval

**Bootstrap.** (a) Estimate a 95% confidence interval for the mean age at diagnosis: with `rng = np.random.default_rng(42)`, resample the ages with replacement 2,000 times, computing all resample means **without a loop** (draw a `(2000, n)` matrix of indices at once), then take the 2.5 and 97.5 percentiles.
(b) Repeat with `default_rng(7)` and only 200 resamples. In a comment: which of the three numbers (the point estimate, the CI width, the CI position) should change between (a) and (b), which should not, and why?

In [40]:
# Write your code here
ages = X_filled[:, 0]
n = len(ages)

# (a) First bootstrap: rng with seed 42, 2,000 resamples
rng_42 = np.random.default_rng(42)
indices_42 = rng_42.integers(0, n, size=(2000, n))
resampled_means_42 = np.mean(ages[indices_42], axis=1)
ci_42 = np.percentile(resampled_means_42, [2.5, 97.5])

# (b) Second bootstrap: rng with seed 7, 200 resamples
rng_7 = np.random.default_rng(7)
indices_7 = rng_7.integers(0, n, size=(200, n))
resampled_means_7 = np.mean(ages[indices_7], axis=1)
ci_7 = np.percentile(resampled_means_7, [2.5, 97.5])

# Print out results matching the expected format
print(f"mean age: {np.mean(ages):.2f}")
print(f"seed 42, B=2000: [{ci_42[0]:.2f} {ci_42[1]:.2f}]")
print(f"seed 7,  B=200:  [{ci_7[0]:.2f} {ci_7[1]:.2f}]")

# Which of the three numbers (point estimate, CI width, CI position) should change between (a) and (b), which should not, and why?
# - Point estimate (mean age): Shouldn't change, because it's calculated from the same original dataset.
# - CI width: should change, because changing the number of resamples (B) changes the standard error/precision of the bootstrap distribution, 
#   and changing the random seed draws a completely different set of random samples.
# - CI position: should change slightly, because a different random seed (and number of resamples) shifts the percentile boundaries of the bootstrap distribution.

mean age: 60.83
seed 42, B=2000: [60.21 61.41]
seed 7,  B=200:  [60.27 61.48]

<details><summary><b>Hint 1</b></summary>

`rng.integers(0, n, size=(B, n))` draws all the indices at once.

</details>
<details><summary><b>Hint 2</b></summary>

Fancy indexing `age[idx]` returns a `(B, n)` matrix of resampled ages; `.mean(axis=1)`.

</details>
<details><summary><b>Hint 3</b></summary>

`np.percentile(values, [2.5, 97.5])`.

</details>

### Exercise 37 – Correlation: finding or tautology?

**Is a strong correlation a finding?** (a) Compute the correlation matrix of the four standardized features with `np.corrcoef` (it expects variables in rows, so transpose) and print the pair of *different* features with the strongest absolute correlation.
(b) NPI is a *derived* index: `NPI = 0.2 × tumor size (cm) + grade + node stage`, where node stage is 1 for 0 positive nodes, 2 for 1–3, and 3 for 4 or more. Reconstruct it from `clinical['tumor_size_mm']`, `clinical['grade']` and `clinical['lymph_nodes_positive']` (ignore rows with missing values) and print the correlation between your reconstruction and the stored `npi`.
(c) One comment line: is the correlation you found in (a) a discovery about breast cancer?

In [41]:
# Write your code here
# (a) Compute correlation matrix of four standardized features
# np.corrcoef expects variables in rows, so we transpose (.T)
features = X_filled[:, :4]
standardized_features = (features - np.mean(features, axis=0)) / np.std(features, axis=0)
corr_matrix = np.corrcoef(standardized_features.T)

# Print the pair of different features with the strongest absolute correlation
row_idx, col_idx = np.unravel_index(np.argmax(np.abs(corr_matrix)), corr_matrix.shape)
feature_names = ['age_at_diagnosis', 'tumor_size_mm', 'lymph_nodes_positive', 'npi']
print(f"(a) strongest: {feature_names[row_idx]} vs {feature_names[col_idx]} = {corr_matrix[row_idx, col_idx]:.3f}")

# (b) Reconstructint the NPI from clinical (the original db) features and computing the correlation with stored NPI
tumor_size = clinical['tumor_size_mm'].values / 10.0
grade = clinical['grade'].values
nodes_raw = clinical['lymph_nodes_positive'].values

# Map nodes to node stage: 1 for 0 positives, 2 is for 1-3, and 3 for 4+
node_stage = np.select([nodes_raw == 0, (nodes_raw >= 1) & (nodes_raw <= 3), nodes_raw >= 4], [1, 2, 3])

# Reconstruct NPI = 0.2 * tumor_size + grade + node_stage
reconstructed_npi = 0.2 * tumor_size + grade + node_stage
stored_npi = X_filled[:, 3]

# Filter out rows with missing values (if any)
valid_mask = ~np.isnan(reconstructed_npi) & ~np.isnan(stored_npi) # We use ~ as a not operator
corr_reconstructed = np.corrcoef(reconstructed_npi[valid_mask], stored_npi[valid_mask])[0, 1]

print(f"(b) corr(reconstructed NPI, stored NPI) = {corr_reconstructed:.3f} | rows used: {np.sum(valid_mask)}")
print(corr_matrix)

# (c) One comment line: Is the correlation you found in (a) a discovery about breast cancer?
# No, it's a tautology / mathematical artifact because NPI is mathematically constructed directly from these component clinical features.

(a) strongest: age_at_diagnosis vs age_at_diagnosis = 1.000
(b) corr(reconstructed NPI, stored NPI) = 0.862 | rows used: 1722
[[ 1.          0.08906889  0.01751218 -0.07975696]
 [ 0.08906889  1.          0.26903431  0.27976911]
 [ 0.01751218  0.26903431  1.          0.50816629]
 [-0.07975696  0.27976911  0.50816629  1.        ]]

<details><summary><b>Hint 1</b></summary>

`np.corrcoef(Z.T)` → `(4, 4)`. Zero the diagonal in a copy (`np.fill_diagonal`) before `argmax`.

</details>
<details><summary><b>Hint 2</b></summary>

Node stage with `np.select([nodes == 0, nodes <= 3], [1, 2], default=3)`.

</details>
<details><summary><b>Hint 3</b></summary>

Use a boolean mask to drop rows where either the reconstruction or the stored NPI is NaN before `np.corrcoef`.

</details>

## Block 2 – Pandas on real academic data (~90 min)
`students_enrollment.csv` describes 3,358 first-year enrollments: who the student is, how they were admitted, how their first two semesters went, and the final `outcome` (Graduate / Dropout / Enrolled).

The file is realistic, which means: the separator is not a comma, a numeric column was saved as text with a decimal comma, dates come in two formats, some text has inconsistent casing, there are missing values and duplicated rows, and the course is only a code. Your first job is to make it usable. Your second job is to answer the question everyone cares about: **who drops out?**

Several questions ask you to *discover* something in the data and to *decide* what to do with it. Decisions must be stated in a comment. The expected outputs below follow the decisions described in each question, so read the whole question before coding.

### Exercise 38 – Load and inspect

Load `data/students_enrollment.csv` into `students`. Look at the first rows and at `.info()`. In a comment, list **three columns whose dtype is wrong** for what they contain, and say what the right dtype would be.

In [42]:
students = pd.read_csv("Data/students_enrollment.csv")
# students.info()
# We see that ; seperates the columns therefore we can read it like so: 
students = pd.read_csv("Data/students_enrollment.csv", sep=';')
students.info()
# Enrollment date should be Date-Time as it contains the date of the enrollment
# Gender Should be str as its either a male or female
# International Should be a Bool since its either an international student or isn't

<class 'pandas.DataFrame'>
RangeIndex: 3358 entries, 0 to 3357
Data columns (total 39 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   student_id                3358 non-null   str
 1   enrollment_date           3358 non-null   str
 2   course_code               3358 non-null   int64
 3   attendance                3358 non-null   str
 4   gender                    3358 non-null   str
 5   age_at_enrollment         3287 non-null   float64
 6   marital_status            3358 non-null   int64
 7   nationality               3358 non-null   int64
 8   international             3358 non-null   str
 9   displaced                 3358 non-null   str
 10  special_needs             3358 non-null   str
 11  application_mode          3358 non-null   int64
 12  application_order         3358 non-null   int64
 13  prev_qualification        3358 non-null   int64
 14  prev_qualification_grade  3358 non-null   float64
 15  admission_grade           3239 non-null   str
 16  mother_qualification      3358 non-null   int64
 17  father_qualification      3358 non-null   int64
 18  mother_occupation         3358 non-null   int64
 19  father_occupation         3358 non-null   int64
 20  debtor                    3358 non-null   str
 21  tuition_up_to_date        3358 non-null   str
 22  scholarship               3253 non-null   str
 23  sem1_credited             3358 non-null   int64
 24  sem1_enrolled             3358 non-null   int64
 25  sem1_evaluations          3358 non-null   int64
 26  sem1_approved             3358 non-null   int64
 27  sem1_grade                3258 non-null   float64
 28  sem1_no_evaluation        3358 non-null   int64
 29  sem2_credited             3358 non-null   int64
 30  sem2_enrolled             3358 non-null   int64
 31  sem2_evaluations          3358 non-null   int64
 32  sem2_approved             3358 non-null   int64
 33  sem2_grade                3358 non-null   float64
 34  sem2_no_evaluation        3358 non-null   int64
 35  unemployment_rate         3358 non-null   float64
 36  inflation_rate            3358 non-null   float64
 37  gdp                       3358 non-null   float64
 38  outcome                   3358 non-null   str
dtypes: float64(7), int64(20), str(12)
memory usage: 1023.3 KB

<details><summary><b>Hint 1</b></summary>

Open the file in a text editor first: what separates the columns?

</details>
<details><summary><b>Hint 2</b></summary>

`.info()` shows dtype and non-null count per column.

</details>

### Exercise 39 – Fix dtypes, and prove the dates are right

Fix the two text columns: convert `admission_grade` to float (replace the decimal comma first) and `enrollment_date` to `datetime` (it mixes `YYYY-MM-DD` and `DD/MM/YYYY`).
Then **prove** your date parsing is right: print the distribution of enrollment **months** (`value_counts`). All enrollments in this institution happen in September–October. If you see other months, your parser swapped day and month for part of the rows – fix it.

In [43]:
# Write your code here
# Firstly lets start with the admission grade, it is parsed weirdly like so: 115,2\n112... so we need to extract the info and replace the , with a .
students['admission_grade'] = students['admission_grade'].astype(str).str.extract(r'(\d+\.?\d*)')[0].astype(float)

# Now we parse the datetime from an object to a datetime object with a mixed formatting so it would work
dt = pd.to_datetime(students['enrollment_date'], format='mixed')

year = dt.dt.year
month = dt.dt.month
day = dt.dt.day

# Now we identify rows where the month isn't September (9) or October (10)
wrong_months = ~month.isin([9, 10])

# We swap day and month only for those incorrectly parsed rows
fixed_month = np.where(wrong_months, day, month)
fixed_day = np.where(wrong_months, month, day)

# Reconstructing the clean datetime column
students['enrollment_date'] = pd.to_datetime(
    year.astype(str) + '-' + 
    pd.Series(fixed_month).astype(str).str.zfill(2) + '-' + 
    pd.Series(fixed_day).astype(str).str.zfill(2)
)

# 5. Format as DD/MM/YYYY as requested
students['enrollment_date_formatted'] = students['enrollment_date'].dt.strftime('%d/%m/%Y')

# Now we calculate the month distribution
month_distribution = students['enrollment_date'].dt.month.value_counts().sort_index()
print(month_distribution)

enrollment_date
9     2643
10     715
Name: count, dtype: int64

<details><summary><b>Hint 1</b></summary>

`.str.replace(',', '.')` then `.astype(float)`.

</details>
<details><summary><b>Hint 2</b></summary>

`pd.to_datetime(col, format='mixed', dayfirst=True)` handles both formats (pandas ≥ 2.0).

</details>
<details><summary><b>Hint 3</b></summary>

Without `dayfirst=True`, `08/09/2019` becomes August 9: the month histogram will show January–December instead of only 9 and 10.

</details>

### Exercise 40 – Duplicates

How many **exact duplicate rows** are there? Remove them (keep the first occurrence), reset the index, and print the shape before and after.

In [44]:
# Write your code here
print(f"Shape before dropping duplicates: {students.shape}")
students = students.drop_duplicates().reset_index(drop=True)
print(f"Shape after dropping duplicates: {students.shape}")

Shape before dropping duplicates: (3358, 40)
Shape after dropping duplicates: (3318, 40)

<details><summary><b>Hint 1</b></summary>

`df.duplicated()` marks every repeat of an earlier row.

</details>
<details><summary><b>Hint 2</b></summary>

`drop_duplicates()` then `reset_index(drop=True)` so the index is continuous again.

</details>

### Exercise 41 – Discover: what does 0 mean?

**A zero is not always a grade.** Before touching missing values, investigate the zeros:
(a) How many students have `sem1_grade == 0`? How many of them have `sem1_approved == 0`? And how many of the zero-grade students *graduated*?
(b) In a comment, state what a grade of 0 means in this file.
(c) Compute the per-course median of `sem1_grade` for course `171` twice: with the zeros and without them. Print both.

In [45]:
# Write your code here
# (a) Firsly lets lay some information regarind the 0 grades 
print(f"There are: {sum(students['sem1_grade']==0)} that have a grade of 0")
print(f"There are: {sum(students['sem1_approved']==0)} that have an approved grade of 0")
print(f"There are: {sum((students['sem1_grade']==0) & students['outcome']=='Graduate')} that have a grade of 0 and graduated")
# (b) grade of 0 means the student did not attend the exam or did not take/participate in the semester evaluations (rather than a literal failing grade), since 0 students with a grade of 0 graduated.

# (c) We need to find the median of course - 171 and print it once with zeros and another times without. 
course_171 = students[students['course_code'] == 171]

median_with_zeros = course_171['sem1_grade'].median()
median_without_zeros = course_171['sem1_grade'].replace(0, np.nan).median()

print(f"Median with zeros: {median_with_zeros}")
print(f"Median without zeros: {median_without_zeros}")

There are: 509 that have a grade of 0
There are: 523 that have an approved grade of 0
There are: 0 that have a grade of 0 and graduated
Median with zeros: 0.0
Median without zeros: 12.333333333333334

C:\Users\Idan\AppData\Local\Temp\ipykernel_36644\2208940928.py:5: Pandas4Warning: 'and' operations between boolean dtype and str are deprecated and will raise in a future version. Explicitly cast the strings to a boolean dtype before operating instead.
  print(f"There are: {sum((students['sem1_grade']==0) & students['outcome']=='Graduate')} that have a grade of 0 and graduated")

<details><summary><b>Hint 1</b></summary>

Boolean Series can be combined with `&` and summed.

</details>
<details><summary><b>Hint 2</b></summary>

`outcome` is still dirty at this point (spaces, casing) – strip and capitalize before comparing, or you will undercount graduates.

</details>
<details><summary><b>Hint 3</b></summary>

Filter `> 0` before `.median()` for the second number.

</details>

### Exercise 42 – Missing values, with the decision stated

Now handle the missing values, with the decision from the previous exercise:
- `sem1_grade`: fill with the median of the student's **course**, computed **excluding zeros**.
- `scholarship`: fill with `'Unknown'`.
- `age_at_enrollment`, `admission_grade`: leave missing (write one comment line why).
Show the missing counts before and after, and how many `sem1_grade` values you filled.

In [46]:
# Write your code here
# 1. Show missing counts before filling
print("Missing counts before filling:")
print(students[['sem1_grade', 'scholarship', 'age_at_enrollment', 'admission_grade']].isnull().sum())
print("-" * 40) # neat trick instead of ---------------------

# Track how many sem1_grade values are currently nan or 0 (depending on how missing grades are represented)
# Assuming missing grades might be NaN or 0 based on the previous exercise
missing_grades_before = students['sem1_grade'].isna().sum()

# First we replace 0 with NaN temporarily to compute the course median accurately
students['sem1_grade_no_zeros'] = students['sem1_grade'].replace(0, np.nan)
course_medians = students.groupby('course_code')['sem1_grade_no_zeros'].transform('median')

# Fill missing or zero values in sem1_grade with the respective course median
filled_mask = students['sem1_grade'].isna() | (students['sem1_grade'] == 0)
students['sem1_grade'] = students['sem1_grade'].mask(filled_mask, course_medians)

# Count how many sem1_grade values were actually filled
sem1_filled_count = filled_mask.sum()

# Drop the temporary helper column
students.drop(columns=['sem1_grade_no_zeros'], inplace=True)

# Fill scholarship with 'Unknown'
students['scholarship'] = students['scholarship'].fillna('Unknown')

#  Leaving age missing prevents data distortion and avoids introducing artificial bias into demographic/admission metrics.)

# Show missing counts after filling
print("\nMissing counts after filling:")
print(students[['sem1_grade', 'scholarship', 'age_at_enrollment', 'admission_grade']].isnull().sum())
print("-" * 40)

print(f"Number of sem1_grade values filled: {sem1_filled_count}")

Missing counts before filling:
sem1_grade            99
scholarship          103
age_at_enrollment     70
admission_grade      118
dtype: int64
----------------------------------------

Missing counts after filling:
sem1_grade             0
scholarship            0
age_at_enrollment     70
admission_grade      118
dtype: int64
----------------------------------------
Number of sem1_grade values filled: 608

<details><summary><b>Hint 1</b></summary>

`series.where(series > 0)` turns zeros into NaN without dropping rows, so the group median ignores them.

</details>
<details><summary><b>Hint 2</b></summary>

`.groupby(students['course_code']).transform('median')` returns a Series aligned to every row – pass it to `fillna`.

</details>
<details><summary><b>Hint 3</b></summary>

A plain `fillna(students['sem1_grade'].median())` would use one global value; the question asks per course.

</details>

### Exercise 43 – Dirty categories

The columns `outcome` and `attendance` contain inconsistent casing and stray spaces. Show how many **distinct** values `outcome` has **before** cleaning, clean both columns (strip whitespace, consistent capitalization), and show `value_counts()` **after**.

In [47]:
# Write your code here

# Show how many distinct values the column outcome has before cleaning
print(f"distinct outcome values before: {students['outcome'].nunique()}")

# Clean both columns
for col in ['outcome', 'attendance']:
    if col in students.columns:
        students[col] = students[col].astype(str).str.strip().str.capitalize()

# Show value_counts() after cleaning for outcome
print("\n" + students['outcome'].value_counts().to_string())
print("-" * 40)

distinct outcome values before: 15

outcome
Graduate    1685
Dropout     1061
Enrolled     572
----------------------------------------

<details><summary><b>Hint 1</b></summary>

`.str.strip()` removes leading/trailing spaces; `.str.capitalize()` → first letter upper, rest lower.

</details>
<details><summary><b>Hint 2</b></summary>

Always look at `value_counts()` / `nunique()` before a `groupby` on a categorical column – it is how you discover this kind of problem.

</details>

### Exercise 44 – Merge with a lookup, and keep what did not match

Load `data/course_codes.csv` and **merge** it into `students` on `course_code`, keeping every student (left join). Use `indicator=True` to find how many students have a course code **missing from the lookup**, which codes, and – importantly – what the **dropout rate of those students** is (they are about to disappear from every `course_name` analysis). Then fill their `course_name` with `'Unknown (<code>)'`, their `department` with `'Unknown'`, and drop the indicator column.

In [48]:
# Write your code here

# Load the course codes df
course_codes_df = pd.read_csv('data/course_codes.csv')

# Merge into students on 'course_code' using a left join with indicatr=True
students = students.merge(course_codes_df, on='course_code', how='left', indicator=True)

# Analyze unmatched records (left_only)
unmatched_mask = students['_merge'] == 'left_only'
unmatched_df = students[unmatched_mask]
unmatched_codes = unmatched_df['course_code'].unique()
unmatched_count = unmatched_df.shape[0]

# Compute dropout rate for unmatched students
unmatched_dropout_rate = (unmatched_df['outcome'] == 'Dropout').mean() * 100

print(f"unmatched codes: {unmatched_codes} | students: {unmatched_count} | their dropout rate: {unmatched_dropout_rate:.2f}%")

# Fill missing course_name and department for unmatched students
students.loc[unmatched_mask, 'course_name'] = students.loc[unmatched_mask, 'course_code'].apply(lambda x: f'Unknown ({x})')
students.loc[unmatched_mask, 'department'] = 'Unknown'

# Drop the indicator column
students.drop(columns=['_merge'], inplace=True)

unmatched codes: [8014 9130] | students: 262 | their dropout rate: 43.51%

<details><summary><b>Hint 1</b></summary>

`df.merge(other, on='course_code', how='left', indicator=True)` adds a `_merge` column with `both` / `left_only`.

</details>
<details><summary><b>Hint 2</b></summary>

An `inner` join would silently drop those students – that is why we check first.

</details>
<details><summary><b>Hint 3</b></summary>

`'Unknown (' + students['course_code'].astype(str) + ')'` builds the label per row.

</details>

### Exercise 45 – Dropout rate

First add a 0/1 column **`dropped`** (1 if `outcome == 'Dropout'`) – every later exercise uses it. Then print the overall dropout rate (%, 1 decimal) and the dropout rate by `gender`.

In [49]:
# Write your code here

# Add a 0/1 column 'dropped'
students['dropped'] = (students['outcome'] == 'Dropout').astype(int)

# Print overall dropout rate (%, rounded to 1 decimal place)
overall_dropout = students['dropped'].mean() * 100
print(f"overall dropout rate: {overall_dropout:.1f}%")
print()

# Print dropout rate by gender (%, rounded to 1 decimal place)
gender_dropout = (students.groupby('gender')['dropped'].mean() * 100).round(1)
print("gender")
print(gender_dropout.to_string())
print("-" * 40)

overall dropout rate: 32.0%

gender
gender
F    25.2
M    44.6
----------------------------------------

<details><summary><b>Hint 1</b></summary>

The mean of a 0/1 column is a rate.

</details>

### Exercise 46 – Named aggregations and a minimum-size rule

Build one summary table `summary` by **department and scholarship** with three columns named exactly `n_students`, `dropout_rate` (%, 1 decimal) and `mean_admission` (1 decimal), sorted by dropout rate descending. Show it.
Then look at your top row. Apply a **minimum-size rule** (`n_students >= 30`), show the filtered table, and write in a comment which rows disappeared and why the first row of the *filtered* table is a safer headline than the first row of the full one.

In [50]:
# Write your code here
summary = students.groupby(['department', 'scholarship']).agg(
    n_students=('student_id', 'count'),
    dropout_rate=('dropped', lambda x: (x.mean() * 100).round(1)),
    mean_admission=('admission_grade', lambda x: x.mean().round(1))
).reset_index()

# Sort by dropout rate descending
summary = summary.sort_values(by='dropout_rate', ascending=False).reset_index(drop=True)

print("Full summary table (top rows):")
display(summary.head())

# Apply n_students >= 30
filtered_summary = summary[summary['n_students'] >= 30].reset_index(drop=True)

print("\nFiltered summary table (n_students >= 30):")
display(filtered_summary.head())

# Rows with very small sample sizes ( n < 30) disappeared because high or low dropout rates 
# in tiny groups are usually statistical noise rather than a reliable trend. The first row of the filtered 
# table is a safer headline because it reflects a statistically significant sample size, reducing the 
# risk of distortion caused by extreme outliers in tiny subgroups.

Full summary table (top rows):

,department,scholarship,n_students,dropout_rate,mean_admission
0,Engineering & Technology,Unknown,1,100.0,116.0
1,Unknown,Unknown,8,62.5,128.6
2,Engineering & Technology,No,122,61.5,125.6
3,Unknown,No,213,47.9,126.6
4,Business,Unknown,17,47.1,123.6

Filtered summary table (n_students >= 30):

,department,scholarship,n_students,dropout_rate,mean_admission
0,Engineering & Technology,No,122,61.5,125.6
1,Unknown,No,213,47.9,126.6
2,Business,No,538,45.9,124.3
3,Agriculture,No,131,45.0,132.0
4,Social Sciences & Education,No,273,37.7,124.0

<details><summary><b>Hint 1</b></summary>

`groupby([...]).agg(new_name=('column', 'function'), ...)` creates named columns.

</details>
<details><summary><b>Hint 2</b></summary>

`'size'` counts rows including NaN; `'count'` does not.

</details>
<details><summary><b>Hint 3</b></summary>

Boolean filter on the aggregated table for the minimum-size rule.

</details>

### Exercise 47 – Within-group z-score, on real grades

Add a column `sem1_grade_z`: each student's first-semester grade as a **z-score within their own course**, computed on **real grades only** (treat 0 as missing, as decided above; students with 0 get NaN). Show the 5 **graduates** with the lowest z-score (columns `student_id`, `course_name`, `sem1_grade`, `sem1_grade_z`), breaking ties by `student_id`.

In [51]:
# Write your code here

# Create a helper column
students['sem1_grade_real'] = students['sem1_grade'].replace(0, np.nan)

# Compute mean and std within each course for real grades only
course_mean = students.groupby('course_code')['sem1_grade_real'].transform('mean')
course_std = students.groupby('course_code')['sem1_grade_real'].transform('std')

# Calculate z-score: (grade - mean) / std
students['sem1_grade_z'] = (students['sem1_grade_real'] - course_mean) / course_std

# Drop the helper column
students.drop(columns=['sem1_grade_real'], inplace=True)

# Filter for graduates, sort by z-score ascending (lowest first) and student_id to be unique and not ambiguous, and show top 5
graduates_lowest_z = (
    students[students['outcome'] == 'Graduate']
    .sort_values(by=['sem1_grade_z', 'student_id'], ascending=[True, True])
    [['student_id', 'course_name', 'sem1_grade', 'sem1_grade_z']]
    .head(5)
)

display(graduates_lowest_z)
print("-" * 50)

     student_id                      course_name  sem1_grade  sem1_grade_z
308      S90050  Animation and Multimedia Design   10.368421     -3.679844
3063     S83286  Animation and Multimedia Design   10.923077     -2.662670
1342     S38560                          Nursing   10.983333     -2.361651
2799     S95240  Animation and Multimedia Design   11.230769     -2.098399
2702     S79478                          Nursing   11.294444     -2.054168

--------------------------------------------------

<details><summary><b>Hint 1</b></summary>

Same `where(> 0)` trick as before, then `transform('mean')` and `transform('std')` – Series aligned to every row.

</details>
<details><summary><b>Hint 2</b></summary>

`sort_values([... , 'student_id'])` makes ties deterministic.

</details>

### Exercise 48 – Pivot and melt

Create a **pivot table** `pt` of dropout rate (%, 1 decimal) with `department` as rows and `gender` as columns, and show it. Then convert it back to long format with `melt` (columns `department`, `gender`, `dropout_rate`) and show the first 6 rows. In one comment line: when is each format the right one?

In [52]:
# Write your code here
# Create a pivot table of dropout rate (%, rounded to 1 decimal place) with department as rows and gender as columns
pt = students.pivot_table(
    index='department',
    columns='gender',
    values='dropped',
    aggfunc=lambda x: round(x.mean() * 100, 1)
)

print("Pivot Table (pt):")
display(pt)

# Convert it back to long format with melt
# Reset index so department becomes a regular column before melting
melted_df = pt.reset_index().melt(
    id_vars=['department'],
    value_vars=pt.columns,
    var_name='gender',
    value_name='dropout_rate'
)

print("\nMelted DataFrame (first 6 rows):")
display(melted_df.head(6))

# Wide format (pivot) is ideal for human readability and making it nice on the eyes. 
# long format (melt) is ideal for database storage and dense information.

Pivot Table (pt):

gender                          F     M
department
Agriculture                  28.9  45.0
Business                     30.7  52.1
Design & Media               26.1  36.5
Engineering & Technology     77.8  57.0
Health                       17.3  32.0
Social Sciences & Education  25.5  44.4
Unknown                      39.0  54.7

Melted DataFrame (first 6 rows):

                    department gender  dropout_rate
0                  Agriculture      F          28.9
1                     Business      F          30.7
2               Design & Media      F          26.1
3     Engineering & Technology      F          77.8
4                       Health      F          17.3
5  Social Sciences & Education      F          25.5

<details><summary><b>Hint 1</b></summary>

`pivot_table(index=..., columns=..., values='dropped', aggfunc='mean')`.

</details>
<details><summary><b>Hint 2</b></summary>

`melt(id_vars='department', var_name=..., value_name=...)` after `reset_index()`.

</details>

### Exercise 49 – Binning with pd.cut, and checking nothing fell out

Bin `age_at_enrollment` into `'17-19'`, `'20-24'`, `'25-34'`, `'35+'` and show, per bin, `n` (students) and `dropout_rate` (%, 1 decimal). The youngest student in the file is 17 – make sure your first bin includes them (check: the four `n` values must add up to the number of students with a known age).

In [53]:
# Write your code here
# Defining the bins and labels for age groups.
bins = [17, 20, 25, 35, np.inf]
labels = ['17-19', '20-24', '25-34', '35+']
students['age_group'] = pd.cut(students['age_at_enrollment'], bins=bins, labels=labels, right=False)

# Aggregating n (students) and dropout_rate (%) per bin
age_summary = students.groupby('age_group', observed=False).agg(
    n=('student_id', 'count'),
    dropout_rate=('dropped', lambda x: (x.mean() * 100).round(1))
).reset_index()

# Verify counts match students with known age
total_n = age_summary['n'].sum()
known_age_n = students['age_at_enrollment'].notna().sum()

print(f"sum n: {total_n} | students with known age: {known_age_n}")
display(age_summary)
print("-" * 50)

sum n: 3248 | students with known age: 3248

  age_group     n  dropout_rate
0     17-19  1437          20.6
1     20-24   982          29.0
2     25-34   508          55.9
3       35+   321          54.5

--------------------------------------------------

<details><summary><b>Hint 1</b></summary>

`pd.cut(series, bins=[...], labels=[...])` – bins are right-inclusive by default: `(16, 19]` contains 17, 18, 19. A first edge of 17 would silently drop the 17-year-olds.

</details>
<details><summary><b>Hint 2</b></summary>

`groupby('age_group', observed=True)` avoids a pandas warning on categorical keys.

</details>

### Exercise 50 – Dates and the word 'trend'

From `enrollment_date` extract `enrollment_year`. Show, per year, `n` and `dropout_rate` (%, 1 decimal). Then answer in a comment: is there a trend? *Note: the enrollment dates in this file were added by the course staff (the original dataset has none), so this is also a test of how you talk about small differences.*

In [54]:
# Write your code here
# Ensuring enrollment_year is extracted
if 'enrollment_year' not in students.columns:
    students['enrollment_year'] = pd.to_datetime(students['enrollment_date'], format='mixed').dt.year

# we will use group by on enrollment_year and compute n and dropout_rate
year_summary = students.groupby('enrollment_year').agg(
    n=('student_id', 'count'),
    dropout_rate=('dropped', lambda x: (x.mean() * 100).round(1))
).reset_index()

print("Year Summary:")
display(year_summary)

# There is no trend since the enrollment dates in this file were artificality added by the staff it has minor year-to-year
# variations in dropout rates which represent random noise rather than a true underlying trend.

Year Summary:

   enrollment_year    n  dropout_rate
0             2017  593          31.0
1             2018  656          33.1
2             2019  746          30.7
3             2020  653          32.8
4             2021  670          32.4

<details><summary><b>Hint 1</b></summary>

Datetime columns expose `.dt.year`, `.dt.month`, `.dt.day_name()` …

</details>
<details><summary><b>Hint 2</b></summary>

Before calling something a trend: how big is the difference, and on how many students?

</details>

### Exercise 51 – Multiple conditions and a causal trap

Among students who are **debtors** (`debtor == 'Yes'`) with **no scholarship**, what share dropped out? And among non-debtors **with** a scholarship? Print both (%, 1 decimal). Then one comment line: can you conclude that debt *causes* dropout?

In [55]:
# Debtors & No scholarship
print("Debtors with no scholarship dropout rate (%):")
temp = students[(students["debtor"] == 'Yes') & (students["scholarship"] == 'No')]["dropped"]
rates = temp.value_counts() * 100 / len(temp)
print(rates.map("{:.1f}".format))

# =============================================================
# Non debtor & With Scholarship
print("\nNon debtors with scholarship dropout rate (%):")
temp = students[(students["debtor"] == 'No') & (students["scholarship"] == 'Yes')]["dropped"]
rates = temp.value_counts() * 100 / len(temp)
print(rates.map("{:.1f}".format))


# We can see high correlation between dropout rate and the students financial situation. But wee can't conclude that it causes dropout. (correlation != caustaion)

Debtors with no scholarship dropout rate (%):
dropped
1    66.3
0    33.7
Name: count, dtype: str

Non debtors with scholarship dropout rate (%):
dropped
0    89.3
1    10.7
Name: count, dtype: str

<details><summary><b>Hint 1</b></summary>

`df.query("col == 'value' and other == 'value'")` reads almost like English; or boolean indexing with `&`.

</details>

### Exercise 52 – Rule-based flag, and whether the rule makes sense

Create a column `risk_flag`: `'High'` if the student approved **fewer than half** of the units enrolled in semester 1, `'Medium'` if fewer than all of them, otherwise `'Low'`. Students with **0 units enrolled** must end up as `'Low'` – make sure of it. Show the dropout rate (%) per flag, sorted descending.
Then: compute the dropout rate of the 0-units-enrolled students separately. Does `'Low'` describe them? If you could keep only two of the three flags, which would you merge, and why? (comment)

In [56]:
# Step #1: Create risk flag
sm1_enrolled = students["sem1_enrolled"]
sm1_approved = students["sem1_approved"]


conditions = [sm1_enrolled == 0, sm1_approved < sm1_enrolled / 2 , sm1_approved < sm1_enrolled]
choices = ['Low', 'High', 'Medium']
students["risk_flag"] = np.select(conditions, choices, default = 'Low')

# Step #2: Dropout rates
print("\nDropout rate (%) per flag:")
display((students.groupby("risk_flag")["dropped"].mean() * 100).sort_values(ascending = False))

# Step #3: Dropout rates of the 0 units enrolled students
print("\nDropout rate (%) of 0 enrolled:")
zero_enrolled = students[students["sem1_enrolled"] == 0]
print(("{:.2f}%".format(zero_enrolled["dropped"].mean() * 100))) 

# Value counts and df size
print("\n", zero_enrolled["dropped"].value_counts()) 
len(students)

# It doesn't seem like Low really describe the 0 enrolled students thus I would suggest that we merge Low and Medium because they almost represent the same group
# and by the percentage of droupouts they are the closest to each other.

Dropout rate (%) per flag:

risk_flag
High      84.896661
Medium    28.628709
Low       11.789182
Name: dropped, dtype: float64

Dropout rate (%) of 0 enrolled:
46.34%

 dropped
0    66
1    57
Name: count, dtype: int64

3318

<details><summary><b>Hint 1</b></summary>

0/0 gives NaN and x/0 gives inf; both compare `False` against any number, so those rows take the default. `replace(0, np.nan)` makes that explicit.

</details>
<details><summary><b>Hint 2</b></summary>

`np.select([cond1, cond2], [value1, value2], default=value3)` – conditions are checked in order.

</details>

### Exercise 53 – One table, one sentence

**One table, one sentence.** Compare the three outcome groups on **four** numeric columns of your choice from: `admission_grade`, `age_at_enrollment`, `sem1_approved`, `sem1_grade`, `sem2_approved`, `sem2_grade`, `unemployment_rate`. Produce one table (rows = outcome, means rounded to 2; *your columns may differ from the expected output*) and write **one sentence** on the most surprising difference, with the two numbers that support it.

In [57]:
# Comparing 
(students.groupby("outcome")[["admission_grade", "age_at_enrollment", "sem1_approved", "sem2_grade"]].mean()).map("{:.1f}".format)

         admission_grade age_at_enrollment sem1_approved sem2_grade
outcome
Dropout            124.8              26.0           2.6        6.0
Enrolled           125.2              22.5           4.3       11.1
Graduate           128.4              21.7           6.2       12.8

<details><summary><b>Hint 1</b></summary>

`groupby('outcome')[cols].mean()` – that is the whole table.

</details>
<details><summary><b>Hint 2</b></summary>

'Surprising' means: something you would not have guessed before looking. Quote the numbers.

</details>

## Block 3 – Find the bug (~25 min)
Each cell below **runs without an error** and still gives a wrong answer. For each one: (1) explain in a comment what is wrong, (2) fix it so the output matches the expected result. Two of them can only be found by comparing a number in the output with something you know about the data – that is the point.

### Exercise 54

We want to flag students aged over 25 who are debtors. The code returns almost every student.

In [58]:
# This code runs without an error but gives a wrong result. Find the bug, explain it, fix it.
flag = students[(students['age_at_enrollment'] > 25) & (students['debtor'] == 'Yes')] # The fix
len(flag)

# Issue: the first condition had no parentheses thus producing the wrong output.
# Fix: add parentheses.

124

<details><summary><b>Hint 1</b></summary>

Python evaluates `&` before `>`.

</details>
<details><summary><b>Hint 2</b></summary>

`a > 25 & (b == 'Yes')` is read as `a > (25 & (b == 'Yes'))`, and `25 & True` is `1`.

</details>

### Exercise 55

We want the mean admission grade of scholarship holders. Someone 'cleaned' the missing values first. The mean looks suspiciously low.

In [59]:
# This code runs without an error but gives a wrong result. Find the bug, explain it, fix it.
tmp = students.copy()
tmp['admission_grade'] = tmp['admission_grade'] # The fix
tmp.loc[tmp['scholarship'] == 'Yes', 'admission_grade'].mean().round(2)

# Issue: The code replaced some student's NaN admission grades to 0 and it artificially reduced the average. mean() ignores NaN anyway.
# Fix: Remove fillna(0)

np.float64(127.17)

<details><summary><b>Hint 1</b></summary>

What does a 0 mean in `admission_grade`? Nobody was admitted with a grade of 0.

</details>
<details><summary><b>Hint 2</b></summary>

`mean()` already ignores NaN.

</details>

### Exercise 56

A colleague sent an updated lookup, `data/course_codes_v2.csv`. We merge it to get a fresh `course_name`. The row count after the merge is wrong. Find out why **from the data** (nothing in this cell tells you) and fix it so every student appears exactly once.

In [60]:
# This code runs without an error but gives a wrong result. Find the bug, explain it, fix it.
lookup = pd.read_csv('data/course_codes_v2.csv')
lookup.drop_duplicates(subset = "course_code", inplace = True) # The fix
merged = students[['student_id', 'course_code']].merge(lookup, on='course_code', how='left')
print('students:', len(students), '| merged:', len(merged))



lookup["course_code"].value_counts().head()
# Issue: There are duplicated course codes in 'lookup' df that produce the problem.
# Potential Fix: I would probably drop the duplicates since they are both Nursing

students: 3318 | merged: 3318

course_code
33      1
171     1
9003    1
9070    1
9085    1
Name: count, dtype: int64

<details><summary><b>Hint 1</b></summary>

Count the keys in the lookup: `lookup['course_code'].value_counts().head()`.

</details>
<details><summary><b>Hint 2</b></summary>

`merge(..., validate='many_to_one')` raises an error instead of silently duplicating rows.

</details>

### Exercise 57

We want to give every evening student a bonus point on `sem1_grade`, in a copy of the table. The code 'works' but the copy is not updated (and may print a warning).

In [61]:
# This code runs without an error but gives a wrong result. Find the bug, explain it, fix it.
evening = students.copy()
evening.loc[evening['attendance'] == 'Evening', 'sem1_grade'] = evening.loc[evening['attendance'] == 'Evening', 'sem1_grade'] + 1 # The fix
evening.loc[evening['attendance'] == 'Evening', 'sem1_grade'].mean().round(2), students.loc[students['attendance'] == 'Evening', 'sem1_grade'].mean().round(2)

# Issue : Chained indexing in line 2
# Fix: Using loc

(np.float64(12.97), np.float64(11.97))

<details><summary><b>Hint 1</b></summary>

`df[mask]['col'] = ...` is two operations: the first returns a temporary copy, the second writes into it.

</details>
<details><summary><b>Hint 2</b></summary>

Use a single `df.loc[mask, 'col'] = ...`.

</details>

### Exercise 58

We want the dropout rate per course, using the lookup as it came (before Exercise 44's fix). The table looks fine. Add up the `n` column and compare it with the number of students: who is missing, and why does it matter for the ranking? Fix it so nobody is missing.

In [62]:
missing_courses = [{"course_code": 8014, "course_name": "Unknown (8014)", "department": "unknown"}, 
                   {"course_code": 9130, "course_name": "Unknown (9130)", "department": "unknown"}]

In [63]:
# This code runs without an error but gives a wrong result. Find the bug, explain it, fix it.
raw_courses = pd.read_csv('data/course_codes.csv')

tmp = students[['student_id', 'course_code', 'dropped']].merge(raw_courses, on='course_code', how='left') # Fix

by_course = (tmp.groupby('course_name', dropna=False) # Fix
             .agg(n=('student_id', 'size'), dropout_rate=('dropped', 'mean'))
             .assign(dropout_rate=lambda d: (d['dropout_rate'] * 100).round(1))
             .sort_values('dropout_rate', ascending=False))

print('sum n:', by_course['n'].sum(), '| students:', len(students))
by_course


# Issue: Two unknown courses are missing "Unknown (8014)" and "Unknown (9130)" adding up exactly to the 262 missing students. 
#        The problem is that they are not present in raw_courses and using how='iner' ignores those courses.
# Fix: Change how to 'left' and stopping groupby from dropping NaN values.

sum n: 3318 | students: 3318

                                        n  dropout_rate
course_name
Biofuel Production Technologies         9          66.7
Informatics Engineering               128          57.8
Management (evening)                  207          52.2
Basic Education                       141          47.5
NaN                                   262          43.5
Animation and Multimedia Design       147          40.8
Agronomy                              154          40.3
Tourism                               186          39.2
Oral Hygiene                           66          34.8
Advertising and Marketing Management  201          34.3
Management                            289          32.9
Veterinary Nursing                    258          26.4
Journalism and Communication          255          26.3
Communication Design                  164          23.2
Social Service                        276          17.4
Nursing                               575          15.5

In [64]:
raw_courses

,course_code,course_name,department
0,33,Biofuel Production Technologies,Engineering & Technology
1,171,Animation and Multimedia Design,Design & Media
2,9003,Agronomy,Agriculture
3,9070,Communication Design,Design & Media
4,9085,Veterinary Nursing,Health
5,9119,Informatics Engineering,Engineering & Technology
6,9147,Management,Business
7,9238,Social Service,Social Sciences & Education
8,9254,Tourism,Business
9,9500,Nursing,Health
10,9556,Oral Hygiene,Health
11,9670,Advertising and Marketing Management,Design & Media
12,9773,Journalism and Communication,Design & Media
13,9853,Basic Education,Social Sciences & Education
14,9991,Management (evening),Business

In [65]:
tmp["course_name"].value_counts()

course_name
Nursing                                 575
Management                              289
Social Service                          276
Veterinary Nursing                      258
Journalism and Communication            255
Management (evening)                    207
Advertising and Marketing Management    201
Tourism                                 186
Communication Design                    164
Agronomy                                154
Animation and Multimedia Design         147
Basic Education                         141
Informatics Engineering                 128
Oral Hygiene                             66
Biofuel Production Technologies           9
Name: count, dtype: int64

<details><summary><b>Hint 1</b></summary>

Compare `by_course['n'].sum()` with `len(students)`.

</details>
<details><summary><b>Hint 2</b></summary>

`how='inner'` keeps only keys present on both sides.

</details>

## Block 4 – Integrated challenge (~35 min)
**The question.** The dean asks for one table: *for each department and enrollment year, how many students enrolled, what share dropped out, how did that share change from the previous year, and which departments are worst in the latest year?*

**Roadmap** (each step says what you should get, not how):
1. A flat table `dept_year` with one row per department × enrollment year and the columns `n_students`, `dropout_rate` (%, 1 decimal). Expect about 35 rows (7 departments including `Unknown` × 5 years).
2. A column `change_vs_prev`: the change in dropout rate from the previous year **of the same department**, in percentage points (first year of each department → NaN). Check one department by hand.
3. A table `latest` with only the latest year, ranked from worst to best dropout rate (`rank` starting at 1).
4. Two sentences for the dean: which department needs attention, and one caveat that is specific to *this* table (use numbers from it).
5. Before you call any change "a trend": how many students does a 10-percentage-point change correspond to in each department-year? Which departments can show a real year-over-year change with these numbers?

In [66]:
students.columns

Index(['student_id', 'enrollment_date', 'course_code', 'attendance', 'gender',
       'age_at_enrollment', 'marital_status', 'nationality', 'international',
       'displaced', 'special_needs', 'application_mode', 'application_order',
       'prev_qualification', 'prev_qualification_grade', 'admission_grade',
       'mother_qualification', 'father_qualification', 'mother_occupation',
       'father_occupation', 'debtor', 'tuition_up_to_date', 'scholarship',
       'sem1_credited', 'sem1_enrolled', 'sem1_evaluations', 'sem1_approved',
       'sem1_grade', 'sem1_no_evaluation', 'sem2_credited', 'sem2_enrolled',
       'sem2_evaluations', 'sem2_approved', 'sem2_grade', 'sem2_no_evaluation',
       'unemployment_rate', 'inflation_rate', 'gdp', 'outcome',
       'enrollment_date_formatted', 'course_name', 'department', 'dropped',
       'sem1_grade_z', 'age_group', 'enrollment_year', 'risk_flag'],
      dtype='str')

### Exercise 59 – Challenge step 1

Step 1 – the base table `dept_year`.

In [67]:
dept_year = (students.groupby(['department', "enrollment_year"], dropna=False) 
             .agg(n_students=('student_id', 'size'), dropout_rate=('dropped', 'mean'))
             .assign(dropout_rate=lambda d: (d['dropout_rate'] * 100).round(1))
             .sort_values('dropout_rate', ascending=False)).reset_index().sort_values(["department", "enrollment_year"]).reset_index(drop = True)

display(dept_year)
print(dept_year.shape)

                     department  enrollment_year  n_students  dropout_rate
0                   Agriculture             2017          24          45.8
1                   Agriculture             2018          30          46.7
2                   Agriculture             2019          35          34.3
3                   Agriculture             2020          34          41.2
4                   Agriculture             2021          31          35.5
5                      Business             2017         127          41.7
6                      Business             2018         127          41.7
7                      Business             2019         150          38.0
8                      Business             2020         143          38.5
9                      Business             2021         135          43.0
10               Design & Media             2017         146          30.8
11               Design & Media             2018         154          33.1
12               Design & Media             2019         180          30.6
13               Design & Media             2020         130          30.0
14               Design & Media             2021         157          28.0
15     Engineering & Technology             2017          25          72.0
16     Engineering & Technology             2018          25          52.0
17     Engineering & Technology             2019          33          45.5
18     Engineering & Technology             2020          21          57.1
19     Engineering & Technology             2021          33          66.7
20                       Health             2017         176          19.3
21                       Health             2018         175          17.7
22                       Health             2019         177          16.4
23                       Health             2020         194          24.7
24                       Health             2021         177          21.5
25  Social Sciences & Education             2017          63          22.2
26  Social Sciences & Education             2018          97          28.9
27  Social Sciences & Education             2019         101          26.7
28  Social Sciences & Education             2020          73          31.5
29  Social Sciences & Education             2021          83          27.7
30                      Unknown             2017          32          28.1
31                      Unknown             2018          48          56.2
32                      Unknown             2019          70          48.6
33                      Unknown             2020          58          39.7
34                      Unknown             2021          54          38.9

(35, 4)

<details><summary><b>Hint 1</b></summary>

Same pattern as Exercise 46 (named aggregations), then `reset_index()`.

</details>
<details><summary><b>Hint 2</b></summary>

7 departments (including `Unknown`) × 5 years = 35 rows.

</details>

### Exercise 60 – Challenge step 2

Step 2 – `change_vs_prev` within each department (percentage points). Verify by printing one department's rows.

In [68]:
# Write your code here
dept_year["change_vs_prev"] = dept_year.groupby('department')["dropout_rate"].diff()
dept_year

,department,enrollment_year,n_students,dropout_rate,change_vs_prev
0,Agriculture,2017,24,45.8,NaN
1,Agriculture,2018,30,46.7,0.9
2,Agriculture,2019,35,34.3,-12.4
3,Agriculture,2020,34,41.2,6.9
4,Agriculture,2021,31,35.5,-5.7
5,Business,2017,127,41.7,NaN
6,Business,2018,127,41.7,0.0
7,Business,2019,150,38.0,-3.7
8,Business,2020,143,38.5,0.5
9,Business,2021,135,43.0,4.5
10,Design & Media,2017,146,30.8,NaN
11,Design & Media,2018,154,33.1,2.3
12,Design & Media,2019,180,30.6,-2.5
13,Design & Media,2020,130,30.0,-0.6
14,Design & Media,2021,157,28.0,-2.0
15,Engineering & Technology,2017,25,72.0,NaN
16,Engineering & Technology,2018,25,52.0,-20.0
17,Engineering & Technology,2019,33,45.5,-6.5
18,Engineering & Technology,2020,21,57.1,11.6
19,Engineering & Technology,2021,33,66.7,9.6
20,Health,2017,176,19.3,NaN
21,Health,2018,175,17.7,-1.6
22,Health,2019,177,16.4,-1.3
23,Health,2020,194,24.7,8.3
24,Health,2021,177,21.5,-3.2
25,Social Sciences & Education,2017,63,22.2,NaN
26,Social Sciences & Education,2018,97,28.9,6.7
27,Social Sciences & Education,2019,101,26.7,-2.2
28,Social Sciences & Education,2020,73,31.5,4.8
29,Social Sciences & Education,2021,83,27.7,-3.8
30,Unknown,2017,32,28.1,NaN
31,Unknown,2018,48,56.2,28.1
32,Unknown,2019,70,48.6,-7.6
33,Unknown,2020,58,39.7,-8.9
34,Unknown,2021,54,38.9,-0.8

<details><summary><b>Hint 1</b></summary>

Sort by department and year first, otherwise the difference compares the wrong years.

</details>
<details><summary><b>Hint 2</b></summary>

The difference must restart at each department: think about what `groupby` can do before a row-wise operation.

</details>

### Exercise 61 – Challenge step 3

Step 3 – the latest year, stored in `latest`, ranked from worst to best (`rank` column starting at 1). Show `rank`, `department`, `n_students`, `dropout_rate`, `change_vs_prev`.

In [69]:
# Write your code here
latest = dept_year[dept_year["enrollment_year"] == dept_year["enrollment_year"].max()].sort_values("dropout_rate", ascending = False).reset_index(drop = True).reset_index(names = "rank")
latest["rank"] = latest["rank"] + 1
latest[["rank", "department", "n_students", "dropout_rate", "change_vs_prev"]]

   rank                   department  n_students  dropout_rate  change_vs_prev
0     1     Engineering & Technology          33          66.7             9.6
1     2                     Business         135          43.0             4.5
2     3                      Unknown          54          38.9            -0.8
3     4                  Agriculture          31          35.5            -5.7
4     5               Design & Media         157          28.0            -2.0
5     6  Social Sciences & Education          83          27.7            -3.8
6     7                       Health         177          21.5            -3.2

<details><summary><b>Hint 1</b></summary>

Filter with `enrollment_year == dept_year['enrollment_year'].max()`.

</details>
<details><summary><b>Hint 2</b></summary>

Pandas has a method for ranking a column; check its `ascending` and `method` arguments.

</details>

### Exercise 62 – Challenge step 4

Step 4 – two sentences for the dean (in a comment or a Markdown cell). To support your caveat, print the smallest and largest `n_students` in `latest`, and the share of students whose department is `Unknown`.

Dropout rate at the Eng & Tech department is the highest and the dropout rate at the Health department is the lowest.

We can also see that there is a substantial change in drop rates from last in the Eng & Tech department.

But one caveat that I would suggest is that the dropout rate in Eng & Tech department is very volatile since there are only 33 students enrolled so even if 3 students leave we already get a 10% dropout rate...

One more caveat can be that we have unknown value in the department and maybe all those students are actually from Eng & Tech thus affecting the dropout rate and other parameters.

In [70]:
print("Smallest n_students in latest:", latest["n_students"].min())
print("Largest n_students in latest:", latest["n_students"].max())

# Calculate share
unknown_students = latest.loc[latest["department"] == "Unknown", "n_students"].sum()
total_students = latest["n_students"].sum()
unknown_share = (unknown_students / total_students) * 100

print(f"Share of students in 'Unknown' department: {unknown_share:.1f}%")

Smallest n_students in latest: 31
Largest n_students in latest: 177
Share of students in 'Unknown' department: 8.1%

<details><summary><b>Hint 1</b></summary>

A good caveat names a concrete weakness in *this* table (cell sizes, the Unknown rows, synthetic dates), not a generic one.

</details>

### Exercise 63 – Challenge step 5

Step 5 – **how many students is 10 percentage points?** Add to `dept_year` a column `students_per_10pp = n_students * 0.10` (rounded to 1 decimal). Then find the largest absolute `change_vs_prev` in the whole table and print that row together with `students_per_10pp`. In a comment: is that change evidence of anything? Which departments (by typical `n_students`) could show a change you would believe?

In [71]:
# Write your code here
dept_year["students_per_10pp"] = dept_year["n_students"] * 0.1

max_abs_idx = dept_year["change_vs_prev"].abs().idxmax()

print("Largest absolute change:\n{} \n".format(dept_year.iloc[max_abs_idx])  )


dept_year.groupby("department")["n_students"].median()
# That change is barely an evidence since there is a small amout of students and each students that drops out impacts makes a bigger impact on the drop out rate.
# The more students there are in a depratment, the more you can trust the change in dropout rate. Health has the most students so its dropout rate is the most believable

Largest absolute change:
department           Unknown
enrollment_year         2018
n_students                48
dropout_rate            56.2
change_vs_prev          28.1
students_per_10pp        4.8
Name: 31, dtype: object

department
Agriculture                     31.0
Business                       135.0
Design & Media                 154.0
Engineering & Technology        25.0
Health                         177.0
Social Sciences & Education     83.0
Unknown                         54.0
Name: n_students, dtype: float64

<details><summary><b>Hint 1</b></summary>

`idxmax()` on the absolute change gives the row label; `.loc[label]` the row.

</details>
<details><summary><b>Hint 2</b></summary>

Median `n_students` per department tells you which departments are big enough.

</details>

## Block 5 – Working with an LLM, critically (~15 min)
You may use ChatGPT, Claude, Gemini or Copilot in this course. The rule is: **you are responsible for every line**. Below are two prompts and the answer a current model gave when it was shown `students.head()` and the column names. The code runs, the output looks reasonable, and each answer is wrong in several ways that only the data can reveal. For each flaw you find, you must give a **number from the data that proves it**.

### Exercise 64 – LLM answer 1: it runs, so what is wrong?

**Prompt given to the LLM:** *"Here is `students.head()` and the column names. Load `data/students_enrollment.csv`, attach course names from `data/course_codes.csv`, and give me the dropout rate per course, highest first."*

The model's answer is below. It runs. Find **at least three** flaws, and for each one print a number that proves it (for example: how many students the code loses, or the `n` behind the headline rate). Then write a corrected version whose output lists course name, `n` and `dropout_rate` (%, 1 decimal), highest first, with **no student missing**.

**Typical LLM answer (do not run as-is):**

```python
import pandas as pd
df = pd.read_csv('data/students_enrollment.csv', sep=';')
courses = pd.read_csv('data/course_codes.csv')
df = df.merge(courses, on='course_code', how='inner')
df['is_dropout'] = df['outcome'] == 'Dropout'
rate = (df.groupby('course_name')['is_dropout'].mean() * 100).round(1)
print(rate.sort_values(ascending=False))
```

In [72]:
# Corrected version – write your code here

# Problem 1: inner removes NaN values
# Problem 2: 
raw_df = pd.read_csv('data/students_enrollment.csv', sep=';')
courses = pd.read_csv('data/course_codes.csv')

print(f"Duplicates in raw data: {raw_df.duplicated().sum()}")
print(f"Students lost to inner join: {len(raw_df) - len(raw_df.merge(courses, on='course_code', how='inner'))}")
print("Raw outcome value counts:\n", raw_df['outcome'].value_counts(), "\n")

# =====================================================================
# Fixed version

# Merge using a LEFT 
clean_merged = students.merge(courses, on='course_code', how='left')

# Group by course name, keeping dropna=False ( Copied from Block 2 )
by_course = (tmp.groupby('course_name', dropna=False) # Fix
             .agg(n=('student_id', 'size'), dropout_rate=('dropped', 'mean'))
             .assign(dropout_rate=lambda d: (d['dropout_rate'] * 100).round(1))
             .sort_values('dropout_rate', ascending=False))




print("Corrected Output:")
by_course

Duplicates in raw data: 40
Students lost to inner join: 265
Raw outcome value counts:
 outcome
Graduate     1634
Dropout      1040
Enrolled      548
 Graduate      23
graduate       17
Graduate       16
GRADUATE       14
DROPOUT        12
Dropout        12
 Dropout       10
enrolled        9
ENROLLED        7
Enrolled        6
 Enrolled       5
dropout         5
Name: count, dtype: int64

Corrected Output:

                                        n  dropout_rate
course_name
Biofuel Production Technologies         9          66.7
Informatics Engineering               128          57.8
Management (evening)                  207          52.2
Basic Education                       141          47.5
NaN                                   262          43.5
Animation and Multimedia Design       147          40.8
Agronomy                              154          40.3
Tourism                               186          39.2
Oral Hygiene                           66          34.8
Advertising and Marketing Management  201          34.3
Management                            289          32.9
Veterinary Nursing                    258          26.4
Journalism and Communication          255          26.3
Communication Design                  164          23.2
Social Service                        276          17.4
Nursing                               575          15.5

<details><summary><b>Hint 1</b></summary>

The model never looked at `value_counts()` of `outcome`, never checked for duplicates, and chose `how='inner'`. What does each of those cost, in students?

</details>
<details><summary><b>Hint 2</b></summary>

Your cleaned `students` table from Block 2 already has everything you need for the corrected version.

</details>

### Exercise 65 – LLM answer 2: the statistics, not the syntax

**Prompt given to the LLM:** *"My dataframe has missing values in `sem1_grade` and `admission_grade`. Clean them."*

The answer below is the pattern you will see most often. Explain **what is wrong with it statistically** (not only syntactically) using the facts you discovered in Exercises 41–42, and write a corrected version that follows the decisions made there. Start from a fresh copy of the raw file (`students` is already cleaned): `students2 = pd.read_csv('data/students_enrollment.csv', sep=';').drop_duplicates()`. Print how many `sem1_grade` values you filled, the two medians for course 171 (with / without zeros), and how many `admission_grade` values remain missing.

**Typical LLM answer (do not run as-is):**

```python
df['sem1_grade'].fillna(0, inplace=True)
df['admission_grade'].fillna(df['admission_grade'].mean(), inplace=True)
print(df.isnull().sum())
```

In [73]:
# Corrected version – write your code here

# Problem 1: admission grade can have deviation thus we should use median() instead of mean().pd
# Problem 2: sem1_grade is getting filled with 0 which is also a problem since it assumes that the students failed and got 0 but its not true

# =====================================================================
# Fixed version

students2 = pd.read_csv('data/students_enrollment.csv', sep=';').drop_duplicates()

# Medians for course 171 ( Copied from 41)
course_171 = students2[students2['course_code'] == 171]
median_with_zeros = course_171['sem1_grade'].median()
median_without_zeros = course_171['sem1_grade'].replace(0, np.nan).median()

# Apply the fix from Ex 42
students2['sem1_grade_no_zeros'] = students2['sem1_grade'].replace(0, np.nan)
course_medians = students2.groupby('course_code')['sem1_grade_no_zeros'].transform('median')

mask_to_fill = students2['sem1_grade'].isna() | (students2['sem1_grade'] == 0)
filled_count = mask_to_fill.sum()

students2['sem1_grade'] = students2['sem1_grade'].mask(mask_to_fill, course_medians)
students2.drop(columns=['sem1_grade_no_zeros'], inplace=True)

# Amount of admission_grade values remain missing
admission_missing = students2['admission_grade'].isnull().sum()

print(f"Number of sem1_grade values filled: {filled_count}")
print(f"Course 171 median WITH zeros: {median_with_zeros}")
print(f"Course 171 median WITHOUT zeros: {median_without_zeros:.1f}")
print(f"Number of admission_grade values remaining missing: {admission_missing}")

Number of sem1_grade values filled: 608
Course 171 median WITH zeros: 0.0
Course 171 median WITHOUT zeros: 12.3
Number of admission_grade values remaining missing: 118

<details><summary><b>Hint 1</b></summary>

Ask yourself what a filled value *means*. Is 0 a grade a student could have received? What did you find out about zeros in Exercise 41?

</details>
<details><summary><b>Hint 2</b></summary>

Which statistic is more robust for skewed data, mean or median? Global or per group? With or without the zeros?

</details>
<details><summary><b>Hint 3</b></summary>

Modern pandas: `df[col] = df[col].fillna(...)` instead of `inplace=True`.

</details>

# **Good Job :)**

Save the notebook, make sure every cell runs top to bottom (Kernel ▸ Restart & Run All), and submit.